development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gc-autofit_development
  pool: 5
  username: gc-autofit
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gc-autofit_test
  pool: 5
  username: gc-autofit
  password:
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gc-autofit_production
  pool: 5
  username: root
  password:
  host: localhost
