Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # In the development environment your application's code is reloaded on
  # every request. This slows down response time but is perfect for development
  # since you don't have to restart the web server when you make code changes.
  config.cache_classes = false

  # Do not eager load code on boot.
  config.eager_load = true

  # Show full error reports and disable caching.
  config.consider_all_requests_local       = true
  config.action_controller.perform_caching = false

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Debug mode disables concatenation and preprocessing of assets.
  # This option may cause significant delays in view rendering with a large
  # number of complex assets.
  config.assets.debug = true

  # Asset digests allow you to set far-future HTTP expiration dates on all assets,
  # yet still be able to expire them through the digest params.
  config.assets.digest = true

  # Adds additional error checking when serving assets at runtime.
  # Checks for improperly declared sprockets dependencies.
  # Raises helpful error messages.
  config.assets.raise_runtime_errors = true
  
  #config.assets.precompile  += %w( print.css )
  # Raises error for missing translations
  # config.action_view.raise_on_missing_translations = true

  #admin domain username and password
  config.admin_username = 'admin'
  config.admin_password = '1d989cc0ce4221aaa7081a43a2877294'

  # Root of apgcms
  config.apgcms_root = "#{Rails.root}/gcms"
  # Internal libraries
  config.apgcms_mz_intensity_dir = "#{config.apgcms_root}/gcmsdb/mz_intensity"
  config.apgcms_metabolite_dir  = "#{config.apgcms_root}/gcmsdb/metabolites"
  config.apgcms_calibration_dir  = "#{config.apgcms_root}/gcmsdb/calibrations"

  # user defined libraries
  # config.apgcms_mz_intensity_tmp_dir = "#{config.apgcms_root}/db_tmp/mz_intensity"
  # # store calibration db generated by users
  # config.apgcms_calibration_tmp_dir = "#{config.apgcms_root}/db_tmp/calibrations"

  # user cases working dir 
  config.apgcms_job_dir = "#{Rails.root}/gcmsjobs"

  # apgcmss' example dir
  config.apgcms_example_dir = "#{config.apgcms_root}/example"

end
